baseurl = "https://typicel.me"
languageCode = "en-us"
paginate = 10
theme = "hello-friend-ng"
title = "typicel"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"

# Subtitle for home
homeSubtitle = "student && software developer"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
images = [""]
keywords = "homepage, blog"

[[params.social]]
name = "github"
url = "https://github.com/typicel"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/typicel/"

[[params.social]]
name = "email"
url = "mailto:tylermack2018@gmail.com"

[taxonomies]
category = "blog"
series = "series"
tag = "tags"

[languages]
[languages.en]
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
keywords = ""
readOtherPosts = "Read other posts"
title = "Tyler McCormick"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "typicel"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"

[[menu.main]]
identifier = "work"
name = "Work Experience"
url = "/work"
